### PR TITLE
Updated android sdk to 5.14.11.14322

### PR DESCRIPTION
**Pull request by pmogollons**
Still need to test it a bit more tomorrow.

### CODE REVIEW

**Review by mieszko4 — COMMENTED** [review]
I quickly tried it and it crashes after starting/joining meeting on Android 11 Emulator

**Comment by pmogollons** [comment]
@mieszko4 what error did you got? I just ran it without issues in android 11 emulator.

**Comment by mieszko4** [comment]
> @mieszko4 what error did you got? I just ran it without issues in android 11 emulator.
> 
> Pls be aware that new sdk required jwtToken on init, key and secret is no longer supported.

Yes, thnx. Init is successful, it crashes after starting a meeting with:
```
FATAL EXCEPTION: main
Process: com.zoomustest, PID: 12654
java.lang.NoSuchMethodError: No static method getOrCreate(Landroid/content/Context;)Landroidx/window/layout/WindowInfoTracker; in class Landroidx/window/layout/WindowInfoTracker; or its super classes (declaration of 'androidx.window.layout.WindowInfoTracker' appears in /data/app/~~w3Y3lWezT1XzyGKNrgiWRw==/com.zoomustest-Bwu3emOiWDEfejL-Yv6jng==/base.apk)
	at com.zipow.videobox.conference.ui.ZmFoldableConfActivity.onCreate(ZmFoldableConfActivity.java:30)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Looks like I need to update some package in test app. 
I am testing on M1 so maybe that's the problem.

**Comment by pmogollons** [comment]
Ill check later today, but have no m1 machine to test it.

**Comment by pmogollons** [comment]
I was able to reproduce in linux, so is not an issue with apple m1. Strangely enough, it works when you set

 ```const enableCustomizedMeetingUI = true;``` 

Seems to be an issue with zoom sdk itself, I tried using v2.1.4 of constraintlayout:constraintlayout, but no possitive result.

Im going to try to update to a newer sdk version and check if it works.

**Comment by mieszko4** [comment]
After updating Android Studio and running `Play` from there it works correctly.
It still does not work when running from terminal. Perhaps Android Studio does something more than what react-native run-android does...

**Comment by pmogollons** [comment]
That even more strange, I will investigate about it.

Also, while trying with the latest sdk in jitpack ```jitpack-zoom-us:5.15.7.15567``` I got a complete different error 

```ERR [Error: Error= 1 (invalidArguments), internalErrorCode=0]```

While jwtToken and domain are sent as params. Probably the issue is with the context param.

**Comment by mieszko4** [comment]
I tried couple of things and I am not sure why there is a difference. Also tried with 5.15 earlier today and did not work.
From the logs Android Studio (I am using `Android Studio Giraffe | 2022.3.1 Patch 1` on M1) does:
```
Executing tasks: [:app:assembleDebug] in project
adb shell am start -n "com.zoomustest/com.zoomustest.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
```
Once it is built and I tap on start/join it always works.

On the other side when I run in terminal:
```
cd android
./gradlew :app:assembleDebug
adb shell am start -n "com.zoomustest/com.zoomustest.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
```
Once it is built and I tap on start/join it always fails.

**Comment by mieszko4** [comment]
This also does not work from Android Studio when I do:
1. Build -> Build Bundle(s) / APK(s) -> Build APK(s)
2. `adb install app/build/outputs/apk/debug/app-debug.apk`

Hence this is not related to `react-native run-android`. Some guesses: something is missing in `AndroidManifest.xml,  some package rendering view should be added, something strips off code too much :)

**Comment by pmogollons** [comment]
Waiting for a response on this thread to check if we can fix this issue.

https://devforum.zoom.us/t/android-zoom-meeting-sdk-crash-after-upgrade-to-5-15-5-15204/93324/13

**Comment by mieszko4** [comment]
I tried with ZoomSDK `5.16.2.16555` (newest) and react-native `0.72.6` (newest). The same crash happens when joining a meeting:
```
FATAL EXCEPTION: main

java.lang.NoSuchMethodError: No static method getOrCreate(Landroid/content/Context;)Landroidx/window/layout/WindowInfoTracker; in class Landroidx/window/layout/WindowInfoTracker; or its super classes (declaration of 'androidx.window.layout.WindowInfoTracker' appears in /data/app/~~sKXIu9hZ73bn3l5jtTV_1g==/com.zoomustest-rMfyRW0dc58oCW5mu9Vp0g==/base.apk)

FATAL EXCEPTION: main
Process: com.zoomustest, PID: 13942
java.lang.NoSuchMethodError: No static method getOrCreate(Landroid/content/Context;)Landroidx/window/layout/WindowInfoTracker; in class Landroidx/window/layout/WindowInfoTracker; or its super classes (declaration of 'androidx.window.layout.WindowInfoTracker' appears in /data/app/~~sKXIu9hZ73bn3l5jtTV_1g==/com.zoomustest-rMfyRW0dc58oCW5mu9Vp0g==/base.apk)
	at com.zipow.videobox.conference.ui.ZmConfActivity.onCreate(ZmConfActivity.java:34)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by mieszko4** [comment]
In https://devforum.zoom.us/t/android-zoom-meeting-sdk-crash-after-upgrade-to-5-15-5-15204/93324/13 they suggest this might be a cache bug in Android Studio:
> Hi [@nrichlearning](https://devforum.zoom.us/u/nrichlearning) , thanks for sharing us the dependencies result. We see some users report there is a bug in Android Studio code caching. So can you please try to run Files-Invalidate caches, and then run Build → Rebuild Project on Android Studio?

**Comment by mieszko4** [comment]
I added my finding with Android Studio Run vs Build in https://devforum.zoom.us/t/android-zoom-meeting-sdk-crash-after-upgrade-to-5-15-5-15204/93324/20?u=mieszko4

**Comment by wilkinson4** [comment]
I'm working on getting further ahead by upgrading the android sdk to 5.16.2.16555 that is building locally for me, but I'm unable to test it until I figure out an issue I've been having with Zoom's JWT's. I'm happy to make a PR from my [forked repo's branch](https://github.com/wilkinson4/react-native-zoom-us/tree/ww/upgrade-to-latest-zoom-sdk). We figured it would be safer for the company if we weren't always running away from a deprecated version of the sdk.

**Comment by NaciyeCelenliEco** [comment]
Hello I also have android crash when join meeting. Using react-native-zoom-us 6.18.1 . Do you have a suggestion ?

**Pull request closed without merging**
