### PR TITLE
Upgrade Android SDK to 5.17.11.20433

### PR DESCRIPTION
**Pull request by alvinle8**
* Change jitpack-zoom-us from from 5.16.2.16555 to 5.17.11.20433
* Bump compileSDK version to 34
* Bumped Android dependencies because we were seeing a blank black screen when accessing the Zoom waiting room

Tested on:
Pixel 4a - Android 13
Pixel 7a - Android 14

Features tested:
- Waiting room
- Reactions
- Chat
- Blurring background
- Video and sound

@cristianblar
@miarevalo10

### CODE REVIEW

**Comment by alvinle8** [comment]
@wilkinson4 @mieszko4 - Hi! Please see the changes above

**Review by wilkinson4 — APPROVED** [review]

**Comment by loe-lobo** [comment]
Hi there.

Is there an estimated time to merge this PR? Is something else missing from it?

Thanks.

**Review by mieszko4 — APPROVED** [review]
Looks good to me.
Great with the detailed testing
Thnx for contributing!

**Comment by mieszko4** [comment]
> @mieszko4 what do we need to do to get this merged?
> 
> The continued living on the edge of the zoom cut off dates is nerve wracking. Would you be open to additional contributors?

Sorry for the delay. I've been busy :)

**Pull request merged**
