### PR TITLE
Fix errors with referencing jitpack version that doesn't exist.

### PR DESCRIPTION
**Pull request by wilkinson4**
Fixes this issue:

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkStagingDebugAarMetadata'.
> Could not resolve all files for configuration ':app:StagingDebugRuntimeClasspath'.
   > Failed to transform mobilertc-5.13.10.12578.aar (com.github.zoom-us-community.jitpack-zoom-us:mobilertc:5.13.10.12578) to match attributes {artifactType=a
ndroid-aar-metadata, org.gradle.status=release}.
      > Could not find mobilertc-5.13.10.12578.aar (com.github.zoom-us-community.jitpack-zoom-us:mobilertc:5.13.10.12578).
        Searched in the following locations:
            https://www.jitpack.io/com/github/zoom-us-community/jitpack-zoom-us/mobilertc/5.13.10.12578/mobilertc-5.13.10.12578.aar
```

### CODE REVIEW

**Comment by cristianblar** [comment]
@wilkinson4 why did you close? I'm having the same exact issue.

**Comment by wilkinson4** [comment]
I don't think this was the issue. I'm still working through figuring out what is going on.

**Comment by wilkinson4** [comment]
@mieszko4 any ideas?

**Comment by mieszko4** [comment]
Let's continue in https://github.com/mieszko4/react-native-zoom-us/issues/311

**Pull request closed without merging**
