### PR TITLE
added MeetingViewsOptions

### PR DESCRIPTION
**Pull request by Anusha1509**
Added MeetingViewOptions to hide meeting Info, participants button, share button, more button, leave button. Also added customized title.

### CODE REVIEW

**Review by mieszko4 — APPROVED** [review]
cool, thnx! I will also add this to typescript

**Comment by mieszko4** [comment]
@Anusha1509 fyi https://github.com/mieszko4/react-native-zoom-us/commit/25aa485a31df46479cc04ad4bdd40fc23bf361e0

**Comment by imshreyansh** [comment]
How to achieve this with IOS ?

**Comment by mieszko4** [comment]
> How to achieve this with IOS ?

Related issue https://github.com/mieszko4/react-native-zoom-us/issues/120

**Pull request merged**
