### PR TITLE
feat: Upgrade Android to 5.13.1

### PR DESCRIPTION
**Pull request by mieszko4**
Based on changelog:

* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-v5-10-3-patch
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-10-6
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-11-0
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-v5-11-1-patch
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-11-3-1
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-11-10
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-12-0
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-for-android-v5-12-1-hotfix-1
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-v5-12-2-patch
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-12-8
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-13-0

## Smoke Test Procedure
The following procedure covers testing of the bridge (initialization and join meeting only).

#### Emulator
1. [x] Development: `yarn android`

#### Real Device
1. [x] Development: `yarn android`
2. [ ] Release: `yarn android --variant=release`

### iOS
*Not tested since Android changes only*

### CODE REVIEW

**Comment by mieszko4** [comment]
Currently having issue with running `startMeeting`/`joinMeeting` building on M1 and running on emulator/real device:
```
java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: JNI CallIntMethodV called with pending exception java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~k6R7I4Hx5NcW9aVoNcxvUA==/com.zoomustest-yy8zWuQ8w_9o1EUxid0x0g==/lib/arm64/libannotate.so"...
```
<details>
<summary>More...</summary>
java_vm_ext.cc:577]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1087)
java_vm_ext.cc:577]   at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:1008)
java_vm_ext.cc:577]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1664)
java_vm_ext.cc:577]   at void com.zipow.videobox.mainboard.module.ZmSdkMainBoard.loadSDKConfAppNativeModules() (ZmSdkMainBoard.java:8)
java_vm_ext.cc:577]   at void com.zipow.videobox.mainboard.module.ZmSdkMainBoard.createConfAppForSdk(java.lang.String) (ZmSdkMainBoard.java:8)
java_vm_ext.cc:577]   at void com.zipow.videobox.VideoBoxApplication.initConfAppForSDK(java.lang.String) (VideoBoxApplication.java:23)
java_vm_ext.cc:577]   at int com.zipow.videobox.VideoBoxApplication.startConfServiceForSDK(android.os.Bundle) (VideoBoxApplication.java:8)
java_vm_ext.cc:577]   at int com.zipow.videobox.ptapp.ConfProcessMgr.createConfProcess(java.lang.String) (ConfProcessMgr.java:13)
java_vm_ext.cc:577]   at void com.zipow.videobox.mainboard.Mainboard.notifyUrlActionImpl(java.lang.String) (Mainboard.java:-2)
java_vm_ext.cc:577]   at void com.zipow.videobox.mainboard.Mainboard.notifyUrlAction(java.lang.String) (Mainboard.java:5)
java_vm_ext.cc:577]   at int com.zipow.videobox.confapp.meeting.premeeting.joinscene.ZMWebStart.startConfrence(android.content.Context) (ZMWebStart.java:37)
java_vm_ext.cc:577]   at boolean com.zipow.videobox.JoinByURLActivity.g(android.net.Uri) (JoinByURLActivity.java:4)
java_vm_ext.cc:577]   at boolean com.zipow.videobox.JoinByURLActivity.a(android.net.Uri, boolean, boolean) (JoinByURLActivity.java:39)
java_vm_ext.cc:577]   at void com.zipow.videobox.JoinByURLActivity.b(android.net.Uri, boolean) (JoinByURLActivity.java:16)
java_vm_ext.cc:577]   at void com.zipow.videobox.JoinByURLActivity.onResume() (JoinByURLActivity.java:133)
java_vm_ext.cc:577]   at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1456)
java_vm_ext.cc:577]   at void android.app.Activity.performResume(boolean, java.lang.String) (Activity.java:8129)
java_vm_ext.cc:577]   at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:4434)
java_vm_ext.cc:577]   at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, java.lang.String) (ActivityThread.java:4476)
java_vm_ext.cc:577]   at void android.app.servertransaction.ResumeActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (ResumeActivityItem.java:52)
java_vm_ext.cc:577]   at void android.app.servertransaction.TransactionExecutor.executeLifecycleState(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:176)
java_vm_ext.cc:577]   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:97)
java_vm_ext.cc:577]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2066)
java_vm_ext.cc:577]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
java_vm_ext.cc:577]   at void android.os.Looper.loop() (Looper.java:223)
java_vm_ext.cc:577]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7656)
java_vm_ext.cc:577]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
java_vm_ext.cc:577]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:592)
java_vm_ext.cc:577]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:947)
java_vm_ext.cc:577] 
java_vm_ext.cc:577]     in call to CallIntMethodV
java_vm_ext.cc:577]     from void com.zipow.videobox.mainboard.Mainboard.notifyUrlActionImpl(java.lang.String)
</details>

### Some related issues:
* https://github.com/android/ndk/issues/329
* https://github.com/microsoft/cpp_client_telemetry/issues/624
* https://github.com/realm/realm-kotlin/issues/694
* https://github.com/facebook/react-native/issues/33191

### Possible useful links:
* https://marketplace.zoom.us/docs/sdk/native-sdks/android/getting-started/prerequisites
* https://medium.com/mobiwise-blog/unsatisfiedlinkerror-problem-on-some-android-devices-b77f2f83837d
* https://github.com/facebook/react-native/blob/v0.68.2/gradle.properties
* https://github.com/realm/realm-kotlin/pull/732/files

**Comment by zvs001** [comment]
#### As I see it doesn't work because we have gradle config:
```
pickFirst '**/x86/libc++_shared.so'
 ```
 
 Without this option we can see that we have 2 `libc++_shared.so` files:
 ```
 > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - /Users/zvsx001/.gradle/caches/transforms-3/aa99d81ac9672962e9eb2af1324cd344/transformed/jetified-react-native-0.68.2/jni/arm64-v8a/libc++_shared.so
      - /Users/zvsx001/.gradle/caches/transforms-3/5fc52b37bb6d8e5b40c276b99d1776ee/transformed/jetified-mobilertc-5.11.0.6883/jni/arm64-v8a/libc++_shared.so
```

#### I checked both files for reference `__emutls_get_address`:

- zoom file has this reference:
```
nm -D /Users/zvsx001/.gradle/caches/transforms-3/5fc52b37bb6d8e5b40c276b99d1776ee/transformed/jetified-mobilertc-5.11.0.6883/jni/arm64-v8a/libc++_shared.so | grep '__emutls_get_address'
```
  **Result:** ` 00000000000ec5bc W __emutls_get_address`
 
 - react file doesn't have it:
 ```
nm -D /Users/zvsx001/.gradle/caches/transforms-3/aa99d81ac9672962e9eb2af1324cd344/transformed/jetified-react-native-0.68.2/jni/arm64-v8a/libc++_shared.so | grep '__emutls_get_address'
```
**Result:** No matchings

#### Summary

I don't know how we can deal with it. 
Probably it can be fixed in newer versions.

**Comment by andrew-schenk** [comment]
@zvs001 perhaps try deleting the libc++_shared.so from react-native.aar

```
% find ./ -name '*.aar'           
.//node_modules/react-native/android/com/facebook/react/react-native/0.69.1/react-native-0.69.1-debug.aar
.//node_modules/react-native/android/com/facebook/react/react-native/0.69.1/react-native-0.69.1-release.aar
```

```
zip -d react-native-0.69.1-debug.aar \*libc++_shared.so
zip -d react-native-0.69.1-release.aar \*libc++_shared.so
```

**Comment by andrew-schenk** [comment]
I tried deleting the react-native-0.69.1-debug.aar copy of libc++_shared.so and made it past the `__emutls_get_address` error.

Now the app crashes when trying to join a meeting with this error.

```
java.lang.RuntimeException: Unable to create service com.zipow.videobox.share.ScreenShareServiceForSDK: java.lang.NullPointerException: Attempt to invoke interface method 'int android.content.SharedPreferences.getInt(java.lang.String, int)' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4953)
        at android.app.ActivityThread.access$1900(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int android.content.SharedPreferences.getInt(java.lang.String, int)' on a null object reference
        at us.zoom.libtools.storage.PreferenceUtil.readIntValue(PreferenceUtil.java:2)
        at us.zoom.sdk.SDKNotificationMgr.showConfNotificationForSDK(SDKNotificationMgr.java:6)
        at com.zipow.videobox.share.ScreenShareServiceForSDK.onCreate(ScreenShareServiceForSDK.java:7)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4940)
        at android.app.ActivityThread.access$1900(ActivityThread.java:310) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8663) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```

**Comment by pmogollons** [comment]
@mieszko4 Ill check it out later this week if I can find a solution to this.

**Comment by rimbener** [comment]
Hello, sorry if it's not the place to comment on this, but I'm not sure where to do it.

Instead of updating to 5.12, can Android Zoom SDK be updated to v5.10.6.6361 first?
I think it could fix issues and will be a more minor effort.
I can help with this but I don't know how to publish `com.github.zoom-us-community:jitpack-zoom-us:5.10.6.6361`

What do you think?

Thanks a lot you for this package BTW.

**Comment by sabishm** [comment]
I tried to create my own native module with latest zoom SDK, I also facing this same issue only if i have reanimated in my package.json. After remove the reanimated package it's working fine.

**Comment by mieszko4** [comment]
> Instead of updating to 5.12, can Android Zoom SDK be updated to v5.10.6.6361 first? I think it could fix issues and will be a more minor effort. I can help with this but I don't know how to publish `com.github.zoom-us-community:jitpack-zoom-us:5.10.6.6361`
> 
> What do you think?

Good point. We could do it but in the long run that will not help..But feel free to create a PR for adding new tag into jitpack. You can see how some other tag was added e.g. https://github.com/zoom-us-community/jitpack-zoom-us/pull/8/files

**Comment by mieszko4** [comment]
> I tried to create my own native module with latest zoom SDK, I also facing this same issue only if i have reanimated in my package.json. After remove the reanimated package it's working fine.

You mean you used `implementation 'com.github.zoom-us-community:jitpack-zoom-us:5.12.2.9109'` ? Could you provide a bit more details :)

**Comment by sabishm** [comment]
I tried for two days for creating the library using implementation 'com.github.zoom-us-community:jitpack-zoom-us:5.12.2.9109' but I am also facing the same issue as libannotate finally I created a native module with mobilertc and commonlib now it's working fine.

**Comment by mieszko4** [comment]
> I tried for two days for creating the library using **implementation 'com.github.zoom-us-community:jitpack-zoom-us:5.12.2.9109'** but I am also facing the same issue as **libannotate** finally I created a native module with **mobilertc** and **commonlib** now it's working fine.

Awesome! You mean you https://reactnative.dev/docs/native-modules-android by "native module"? I am wondering why that would work... Would be great if you could share.

**Comment by sabishm** [comment]
Yes, Now I am using my own native module for the android platform, and for iOS I am using your library.

**Pull request merged**
